"""01_initial-db

Revision ID: 5f7b88770bed
Revises: 
Create Date: 2023-07-05 16:14:41.944222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7b88770bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    insert into urls (key, secret_key, target_url, is_active, clicks) values ('test', '123', 'https://ru.hexlet.io/', true, 12)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    delete from urls where key='test'
    """)
    # ### end Alembic commands ###
